<?php

/**
 * Implements hook_wizard
 */
function steps_example_wizard() {
  $wizard = array();
  
  $wizard['evento'] = array(
    'title' => 'Evento',
    'main_path' => 'settings/evento',
    'start_path' => 'settings/evento/costo',
    'end_path' => 'settings/evento/gracias',
  );
  
  return $wizard;
}

/**
 * Implements hook_steps
 */
function steps_example_steps() {
  // Build steps for Wizard 'evento'
  $steps = array();
  
  $steps['costo'] = array(
    'wizard' => 'evento',
    'path' => 'settings/evento/costo',
    'component' => array(
      'type' => 'radios',
      'options' => array(
        'yes' => t("Yes"),
        'no' => t("No"),
      ),
      'validation' => array(
        'yes' => 'settings/evento/instrucciones-con-costo',
        'no' => 'settings/evento/fechas',
      ),
      'default' => 'no',
    ),
    'title' => t("Evento tiene costo?"),
    'description' => t("Please select if this event has any cost"),
  );
  
  $steps['instrucciones-con-costo'] = array(
    'wizard' => 'evento',
    'path' => 'settings/evento/instrucciones-con-costo',
    'component' => array(
      'type' => 'textarea',
      'redirect' => 'settings/evento/fechas'
    ),
    'title' => 'Instrucciones de evento con costo',
    'description' => t("Escriba las instrucciones y precio del evento"),
  );
  
  $steps['fechas'] = array(
    'wizard' => 'evento',
    'path' => "settings/evento/fechas",
    'component' => array(
      'type' => 'form',
      'callback' => '_custom_form_fechas',
      'redirect' => 'settings/evento/gracias'
    ),
    'title' => t("Fechas")
  );
  
  $steps['gracias'] = array(
    'wizard' => 'evento',
    'path' => 'settings/evento/gracias',
    'title' => 'Gracias',
    'component' => array(
      'type' => 'markup',
      'value' => t("Gracias. Ha terminado la configuración"),
      'redirect' => STEP_IS_FINAL,
    ),
  );
  
  return $steps;
}

function steps_example_fechas_form(&$form) {
  $form['tid'] = array(
    '#type' => 'value',
    '#value' => "hello",
  );
  
  $form['sel'] = array(
    '#type' => 'select',
    '#title' => 'Select me',
    '#options' => array(
      'no', 'yes', 'maybe',
    ),
  );
  
  $form['start_date'] = array(
    '#type' => 'textfield',
    '#title' => 'Start date',
    '#description' => t("test")
  );
  
  $form['end_date'] = array(
    '#type' => 'textfield',
    '#title' => 'End date',
  );
  
  // Don't implement any redirects here
  $form['#submit'][] = "steps_example_fechas_form_submit";
  
}

/**
 * Don't implement any redirects of any kind here, remember that
 * after this submit callback is processed, Steps will keep running
 * all the submit process
 * 
 * Process anything independently but remember to do anything you need to do
 * steps will not interfiere here, once the submit callback finishes, it will
 * continue the normal process
 */
function steps_example_fechas_form_submit($form, &$form_state) {
  // Save values to the watchdog
  watchdog("steps_example", $form_state['values']['start_date']);
  watchdog("steps_example", $form_state['values']['end_date']);
}

/**
 * Implement hook_steps_$wizard()
 */
function steps_example_steps_evento(&$data) {
  // dsm($object);
  foreach($data as $obj) {
    watchdog("steps_example", "Let's do something with the object, like printing the step " . $obj['step'] . "and its value " . $obj['value']);  
  }
} 